name: Build Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o hello-${{ matrix.goos }}-${{ matrix.goarch }} main.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hello-${{ matrix.goos }}-${{ matrix.goarch }}
          path: hello-${{ matrix.goos }}-${{ matrix.goarch }}
